apiVersion: v1
kind: Service
metadata:
  name: {{ include "chili.fullname" . }}-api
  labels:
    {{- include "chili.componentLabels" (dict "context" . "component" "api") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "chili.selectorLabels" (dict "context" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
