apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chili.fullname" . }}-app
  labels:
    {{- include "chili.componentLabels" (dict "context" . "component" "app") | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.app }}
  selector:
    matchLabels:
      {{- include "chili.selectorLabels" (dict "context" . "component" "app") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chili.selectorLabels" (dict "context" . "component" "app") | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            {{- if .Values.tls.enabled }}
            - name: https
              containerPort: 443
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources.app | nindent 12 }}
          {{- if .Values.tls.enabled }}
          volumeMounts:
            - name: tls
              mountPath: /etc/nginx/tls
              readOnly: true
          {{- end }}
      {{- if .Values.tls.enabled }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName | quote }}
      {{- end }}
