apiVersion: v1
kind: Service
metadata:
  name: {{ include "chili.fullname" . }}-app
  labels:
    {{- include "chili.componentLabels" (dict "context" . "component" "app") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "chili.selectorLabels" (dict "context" . "component" "app") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    {{- if .Values.tls.enabled }}
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    {{- end }}
