apiVersion: v1
kind: Service
metadata:
  name: chili-api
  labels:
    app.kubernetes.io/name: chili
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chili
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
