"""Internal domain models for policy intelligence."""

from __future__ import annotations

from datetime import datetime
from typing import Literal, cast

from pydantic import BaseModel, Field

from shared.utils import utc_now

PolicyItemStatus = Literal["open", "accepted", "rejected", "deferred", "escalated"]
PolicySeverity = Literal["medium", "high", "critical"]
PolicyTargetKind = Literal["entity", "alert", "metric"]
TriageAction = Literal["accept", "reject", "defer", "escalate"]

# Maps a triage action verb to its resulting item status.
ACTION_TO_STATUS: dict[TriageAction, PolicyItemStatus] = {
    "accept": "accepted",
    "reject": "rejected",
    "defer": "deferred",
    "escalate": "escalated",
}

MatchedValue = str | float | int | bool


class PolicyCitation(BaseModel):
    """A policy/document reference attached to a matched item."""

    citation_id: str
    title: str
    source_ref: str
    excerpt: str | None = None


class PolicyDisposition(BaseModel):
    """The recorded triage decision for an item."""

    action: TriageAction
    actor: str
    note: str | None = None
    decided_at: datetime
    case_id: str | None = None


class PolicyItem(BaseModel):
    """A durable, KB-scoped policy review item generated by a configured rule."""

    id: str
    knowledge_base_id: str
    rule_id: str
    rule_pack_id: str
    target_kind: PolicyTargetKind
    target_ref: str
    title: str
    severity: PolicySeverity
    matched_fields: dict[str, MatchedValue] = Field(
        default_factory=lambda: cast(dict[str, MatchedValue], {})
    )
    citations: list[PolicyCitation] = Field(
        default_factory=lambda: cast(list[PolicyCitation], [])
    )
    status: PolicyItemStatus = "open"
    disposition: PolicyDisposition | None = None
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


__all__ = [
    "ACTION_TO_STATUS",
    "MatchedValue",
    "PolicyCitation",
    "PolicyDisposition",
    "PolicyItem",
    "PolicyItemStatus",
    "PolicySeverity",
    "PolicyTargetKind",
    "TriageAction",
]
